quarkus.log.category."com.quest".level = DEBUG

# Configuration JPA
quarkus.datasource.db-kind = mysql
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/projet_quest
quarkus.datasource.username = root
quarkus.datasource.password =

# DDL pour ajouter tables / colonnes
# quarkus.hibernate-orm.database.generation = update
quarkus.hibernate-orm.schema-management.strategy = update

# Afficher les requêtes SQL générées par Hibernate
quarkus.hibernate-orm.log.sql = true

# Configuration des accès
quarkus.http.auth.permission.auth.paths = /api/auth
quarkus.http.auth.permission.auth.methods = POST
quarkus.http.auth.permission.auth.policy = permit

quarkus.http.auth.permission.api.paths = /api/*
quarkus.http.auth.permission.api.policy = authenticated

# Configuration CORS
quarkus.http.cors.enabled = true
quarkus.http.cors.origins = http://localhost:4200


# Configuration JWT
# - Activation de JWT
quarkus.smallrye-jwt.enabled = true

# - Clé privée pour signer JWT
smallrye.jwt.sign.key.location = classpath:privateKey.pem

# - Configuration de la durée de vie du jeton à 1h
smallrye.jwt.new-token.lifespan = 3600

# - Vérification du jeton
mp.jwt.verify.issuer = quest-quarkus-issuer
mp.jwt.verify.publickey.location = classpath:publicKey.pem
