name: quest

services:
  mysql:
    image: mysql:8.0.45
    container_name: quest-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./quest-init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

    networks:
      - quest

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 5s

  java:
    image: ajc/quest-boot
    container_name: quest-boot

    networks:
      - quest

    ports:
      - 8080:8080

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://quest-mysql:3306/projet_quest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

  angular:
    image: ajc/quest-angular
    container_name: quest-angular

    networks:
      - quest

    ports:
      - 80:80

    depends_on:
      - java

networks:
  quest:
    name: quest

volumes:
  mysql_data:
    name: quest-mysql-data
