spring.application.name = service-security

server.port = 8080

spring.datasource.url = jdbc:mysql://localhost:3306/microservice_security
spring.datasource.username = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

ajc.security.private-key = classpath:privateKey.pem
ajc.security.public-key = classpath:publicKey.pem
