quarkus.http.port = 8081

quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/ms_eshop_client
quarkus.datasource.username = root

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql = true

quarkus.rest-client.commande-service.url = http://localhost:8084/api/commande
