spring.application.name=Biblio

spring.datasource.driver=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/eshop
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.total=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.format-sql=true
