quarkus.package.type = uber-jar

quarkus.http.root-path = /api

# Activer les loggers pour le package quest
quarkus.log.category."fr.bibliotek".level = DEBUG

# Configuration JPA/HIBERNATE avec Panache
quarkus.datasource.db-kind = mysql
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/bibliotek
quarkus.datasource.username = root
quarkus.datasource.password =

# -- Permet de générer les tables, colonnes, etc.
quarkus.hibernate-orm.schema-management.strategy = update

# -- Permet d'afficher les requêtes SQL en log
quarkus.hibernate-orm.log.format-sql = false
quarkus.hibernate-orm.log.sql = true

# Configuration CORS
quarkus.http.cors.enabled = true
quarkus.http.cors.origins = *

# Configuration des accès généraux
quarkus.http.auth.permission.auth-or-register.paths = /api/auth, /api/utilisateur/inscription
quarkus.http.auth.permission.auth-or-register.policy = permit

quarkus.http.auth.permission.api.paths = /*
quarkus.http.auth.permission.api.policy = authenticated

# Configuration JWT
# -- Permet d'activer JWT
quarkus.smallrye-jwt.enabled = true

# -- Permet de préciser la clé de signature du jeton
smallrye.jwt.sign.key.location = classpath:privateKey.pem

# -- On augmente la durée de validité du jeton
smallrye.jwt.new-token.lifespan = 3600

# -- Permet de préciser le fournisseur du jeton et la clé publique de validation du jeton
mp.jwt.verify.issuer = bibliotek-quarkus-issuer
mp.jwt.verify.publickey.location = classpath:publicKey.pem
