
quarkus.http.host = 0.0.0.0


# Configuration JPA
quarkus.datasource.db-kind = mysql
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/quarkus
quarkus.datasource.username = root
quarkus.datasource.password =

# DDL pour ajouter tables / colonnes
quarkus.hibernate-orm.database.generation = update

# Afficher les requêtes SQL générées par Hibernate
quarkus.hibernate-orm.log.sql = true

# # Activer la configuration des utilisateurs en mémoire, avec mot de passe en clair
# quarkus.security.users.embedded.enabled = true
# quarkus.security.users.embedded.plain-text = true

# # Configuration d'un utilisateur jeremy, avec le role admin
# quarkus.security.users.embedded.users.jeremy = 123456
# quarkus.security.users.embedded.roles.jeremy = admin

# quarkus.security.users.embedded.users.user = 123456
# quarkus.security.users.embedded.roles.user = user

# # Définition des politiques
# quarkus.http.auth.policy.role-policy-user.roles-allowed = user, admin
# quarkus.http.auth.policy.role-policy-admin.roles-allowed = admin


# # On dit que tout le monde a droit de voir la liste des produits
# quarkus.http.auth.permission.produit-all.paths = /api/produit
# quarkus.http.auth.permission.produit-all.methods = GET
# quarkus.http.auth.permission.produit-all.policy = permit

# # On dit que tout le monde a droit de s'inscrire
# quarkus.http.auth.permission.subscribe.paths = /api/inscription
# quarkus.http.auth.permission.subscribe.methods = POST
# quarkus.http.auth.permission.subscribe.policy = permit

# # On dit que seul les rôles user ont le droit de voir un produit
# quarkus.http.auth.permission.produit-id.paths = /api/produit/*
# quarkus.http.auth.permission.produit-id.methods = GET
# quarkus.http.auth.permission.produit-id.policy = role-policy-user


# # On dit que seul les rôles admin ont le droit d'ajouter, modifier, supprimer un produit
# quarkus.http.auth.permission.produit-admin.paths = /api/produit, /api/produit/*
# quarkus.http.auth.permission.produit-admin.methods = POST,PUT,DELETE
# quarkus.http.auth.permission.produit-admin.policy = role-policy-admin

# # quarkus.http.auth.permission.produit-admin.paths = /api/produit/*
# # quarkus.http.auth.permission.produit-admin.methods = PUT,DELETE
# # quarkus.http.auth.permission.produit-admin.policy = role-policy-admin

# # quarkus.http.auth.permission.produit-admin-post.paths = /api/produit
# # quarkus.http.auth.permission.produit-admin-post.methods = POST
# # quarkus.http.auth.permission.produit-admin-post.policy = role-policy-admin

# Configuration JWT
# - Activation de JWT
quarkus.smallrye-jwt.enabled = true

# - Clé privée pour signer JWT
smallrye.jwt.sign.key.location = classpath:privateKey.pem

# - Configuration de la durée de vie du jeton à 1h
smallrye.jwt.new-token.lifespan = 3600

# - Vérification du jeton
mp.jwt.verify.issuer = formation-quarkus-issuer
mp.jwt.verify.publickey.location = classpath:publicKey.pem
