
quarkus.http.host = 0.0.0.0


# Configuration JPA
quarkus.datasource.db-kind = mysql
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/quarkus
quarkus.datasource.username = root
quarkus.datasource.password =

# DDL pour ajouter tables / colonnes
quarkus.hibernate-orm.database.generation = update

# Afficher les requêtes SQL générées par Hibernate
quarkus.hibernate-orm.log.sql = true

# Activer la configuration des utilisateurs en mémoire, avec mot de passe en clair
quarkus.security.users.embedded.enabled = true
quarkus.security.users.embedded.plain-text = true

# Configuration d'un utilisateur jeremy, avec le role admin
quarkus.security.users.embedded.users.jeremy = 123456
quarkus.security.users.embedded.roles.jeremy = admin

# On autorise uniquement les utilisateurs connectés
quarkus.http.auth.permission.api.paths = /*
quarkus.http.auth.permission.api.policy = authenticated
