# Le nom du compose, optionel
name: demo-compose

# Décrire tous les services, volumes, network, etc. nécessaire au bon fonctionnement

# Descrription des différents containers
services:
  # Description du container "mysql"
  # docker run -d -e MYSQL_ROOT_PASSWORD=root --name quest-mysql --network quest -v "D:/ajc/quest-init.sql":/docker-entrypoint-initdb.d/init.sql mysql:8.0.45
  mysql:
    image: mysql:8.0.45
    container_name: demo-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      # Pour initialiser la base
      - ./demo-init.sql:/docker-entrypoint-initdb.d/init.sql

      # Pour persister les données après suppression / mise à jour du container
      - mysql_data:/var/lib/mysql

    networks:
      - cledemorso

    # ports:
    #   - 3308:3306

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 5s

  java:
    image: XXX
    container_name: XXXXX

    networks:
      - cledemorso

    depends_on:
      # - mysql

      # On va attendre que mysql démarre ET qu'il soit prêt à être utilisé
      mysql:
        condition: service_healthy

networks:
  cledemorso:
    name: demo-nom-rso

volumes:
  mysql_data:
    name: demo-mysql-data
