spring.application.name=formation-tdd

spring.jpa.hibernate.ddl-auto = update

# Permet de déplacer DDL AUTO Après l'exécution du contexte de Spring et AVANT l'exécution de data.sql
spring.jpa.defer-datasource-initialization = true
