spring.application.name=formation-tdd

logging.level.fr.formation = DEBUG
logging.level.org.springframework = ERROR
logging.level.org.hibernate = ERROR

spring.jpa.hibernate.ddl-auto = update

# Permet de déplacer DDL AUTO Après l'exécution du contexte de Spring et AVANT l'exécution de data.sql
spring.jpa.defer-datasource-initialization = true
