name: quest

# Décrire tous les services, volumes, network, etc. nécessaire au bon fonctionnement

# Descrription des différents containers
services:
  # Description du container "mysql"
  # docker run -d -e MYSQL_ROOT_PASSWORD=root --name quest-mysql --network quest -v "D:/ajc/quest-init.sql":/docker-entrypoint-initdb.d/init.sql mysql:8.0.45
  mysql:
    image: mysql:8.0.45
    container_name: quest-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      # Pour initialiser la base
      - ./quest-init.sql:/docker-entrypoint-initdb.d/init.sql

      # Pour persister les données après suppression / mise à jour du container
      - mysql_data:/var/lib/mysql

    networks:
      - quest

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 5s

  postgres:
    image: postgres:18.3
    container_name: quest-postgres

    environment:
      POSTGRES_PASSWORD: root

    volumes:
      # Pour initialiser la base
      - ./quest-init.sql:/docker-entrypoint-initdb.d/init.sql

      # Pour persister les données après suppression / mise à jour du container
      - postgres_data:/var/lib/postgresql/18/docker

    networks:
      - quest

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "projet_quest" ]
      timeout: 3s
      retries: 10
      interval: 5s

  java:
    image: ajc-quest-boot
    container_name: quest-boot

    networks:
      - quest

    ports:
      - 8080:8080

    environment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://quest-mysql:3306/projet_quest
      SPRING_DATASOURCE_URL: jdbc:postgresql://quest-postgres:5432/projet_quest
      SPRING_DATASOURCE_USERNAME: postgres

    depends_on:
      # On va attendre que mysql démarre ET qu'il soit prêt à être utilisé
      mysql:
        condition: service_healthy

      postgres:
        condition: service_healthy

  angular:
    image: ajc-quest-angular
    container_name: quest-angular

    networks:
      - quest

    ports:
      - 80:80

    depends_on:
      - java

networks:
  quest:
    name: quest

volumes:
  mysql_data:
    name: quest-mysql-data

  postgres_data:
    name: quest-postgres-data
